/** @type {import('tailwindcss').Config} */
export default {
	content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
	darkMode: "class",
	theme: {
		extend: {
			colors: {
				surface: "#f8f9ff",
				"surface-dim": "#cbdbf5",
				"surface-bright": "#f8f9ff",
				"surface-container-lowest": "#ffffff",
				"surface-container-low": "#eff4ff",
				"surface-container": "#e5eeff",
				"surface-container-high": "#dce9ff",
				"surface-container-highest": "#d3e4fe",
				"on-surface": "#0b1c30",
				"on-surface-variant": "#464555",
				"inverse-surface": "#213145",
				"inverse-on-surface": "#eaf1ff",
				outline: "#777587",
				"outline-variant": "#c7c4d8",
				"surface-tint": "#4d44e3",
				primary: "#3525cd",
				"on-primary": "#ffffff",
				"primary-container": "#4f46e5",
				"on-primary-container": "#dad7ff",
				"inverse-primary": "#c3c0ff",
				secondary: "#006591",
				"on-secondary": "#ffffff",
				"secondary-container": "#39b8fd",
				"on-secondary-container": "#004666",
				tertiary: "#7e3000",
				"on-tertiary": "#ffffff",
				"tertiary-container": "#a44100",
				"on-tertiary-container": "#ffd2be",
				error: "#ba1a1a",
				"on-error": "#ffffff",
				"error-container": "#ffdad6",
				"on-error-container": "#93000a",
				"primary-fixed": "#e2dfff",
				"primary-fixed-dim": "#c3c0ff",
				"on-primary-fixed": "#0f0069",
				"on-primary-fixed-variant": "#3323cc",
				"secondary-fixed": "#c9e6ff",
				"secondary-fixed-dim": "#89ceff",
				"on-secondary-fixed": "#001e2f",
				"on-secondary-fixed-variant": "#004c6e",
				"tertiary-fixed": "#ffdbcc",
				"tertiary-fixed-dim": "#ffb695",
				"on-tertiary-fixed": "#351000",
				"on-tertiary-fixed-variant": "#7b2f00",
				background: "#f8f9ff",
				"on-background": "#0b1c30",
				"surface-variant": "#d3e4fe",
			},
			borderRadius: {
				DEFAULT: "0.125rem",
				lg: "0.25rem",
				xl: "0.5rem",
				"2xl": "1rem",
				full: "9999px",
			},
			fontFamily: {
				display: ["Inter", "sans-serif"],
				"body-base": ["Inter", "sans-serif"],
				"body-sm": ["Inter", "sans-serif"],
				"headline-md": ["Inter", "sans-serif"],
				"label-caps": ["Inter", "sans-serif"],
				"mono-input": [
					"ui-monospace",
					"SFMono-Regular",
					"Menlo",
					"Monaco",
					"Consolas",
					"monospace",
				],
			},
			fontSize: {
				display: [
					"30px",
					{ lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" },
				],
				"mono-input": ["15px", { lineHeight: "24px", fontWeight: "400" }],
				"body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
				"body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
				"headline-md": [
					"20px",
					{ lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" },
				],
				"label-caps": [
					"12px",
					{ lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
				],
			},
			spacing: {
				gutter: "1.5rem",
				"stack-sm": "0.5rem",
				"stack-md": "1rem",
				"stack-lg": "2rem",
				"container-max": "1024px",
			},
		},
	},
	plugins: [],
};
